# Generated by Django 2.2.7 on 2019-12-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20191208_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('pat_id', models.IntegerField()),
                ('doc_id', models.IntegerField()),
                ('appointment_status', models.BooleanField(default=False)),
                ('payment_status', models.BooleanField(default=False)),
                ('date', models.DateField(null=True)),
                ('reason', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_img'),
        ),
    ]
