# Generated by Django 2.2.7 on 2019-12-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20191213_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appdate',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reject_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
