# Generated by Django 2.2.7 on 2020-01-08 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20191220_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='receiver',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
