# Generated by Django 2.2.7 on 2020-01-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_auto_20200108_0601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatdb',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('pat_id', models.IntegerField()),
                ('doc_id', models.IntegerField()),
                ('chat_status', models.BooleanField(default=False)),
                ('payment_status', models.BooleanField(default=False)),
                ('reject_status', models.BooleanField(default=False)),
                ('fees', models.IntegerField(null=True)),
                ('txnid', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
