# Generated by Django 2.2.7 on 2020-01-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_chatdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='user',
        ),
        migrations.AddField(
            model_name='chat',
            name='sender',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='chatdb',
            name='closed',
            field=models.BooleanField(default=True),
        ),
    ]
