# Generated by Django 2.2.7 on 2020-01-22 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_auto_20200122_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_img/'),
        ),
    ]
