# Generated by Django 2.2.7 on 2019-12-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='pin',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialist',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
