# Generated by Django 2.2.7 on 2019-12-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20191209_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='fees',
            field=models.IntegerField(default=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='language',
            field=models.CharField(default='English', max_length=30, null=True),
        ),
    ]
