# Generated by Django 2.2.7 on 2019-12-15 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('doctor', '0006_consultdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fees', models.IntegerField(null=True)),
                ('time', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
